In [ ]:
import numpy as np

* Task 01

In [ ]:
class MinHeap:
  def __init__(self,capacity):
    self.__capacity = capacity
    self.__heap = np.zeros(capacity,dtype = int)
    self.__size = 0

  def insertion(self,value):
    if self.__size == self.__capacity:
      return "Heap is full, Insertion is not possible."
    self.__size+=1
    self.__heap[self.__size] = value
    self.swim()

  def swim(self):
    child = self.__size
    parent = child // 2

    while self.__heap[parent] > self.__heap[child]:
        self.__heap[parent], self.__heap[child] = self.__heap[child], self.__heap[parent]
        child = parent
        parent = child//2

  def deletion(self):
    if self.__size == 0:
      return "Heap is empty, Deletion is not possible"
    value = self.__heap[1]
    self.__heap[1],self.__heap[self.__size] = self.__heap[self.__size],self.__heap[1]
    self.__size -=1
    self.sink()
    return value

  def sink(self):
    parent = 1
    while True:
        left = 2 * parent
        if left > self.__size:
            break
        right = left + 1

        min_child = left
        if right <= self.__size and self.__heap[right] < self.__heap[left]:
            min_child = right

        if self.__heap[parent] > self.__heap[min_child]:
            self.__heap[parent], self.__heap[min_child] = self.__heap[min_child], self.__heap[parent]
            parent = min_child
        else:
            break

  def extractMin(self):
    if self.__size == 0:
      return "Heap is empty"
    return self.__heap[1]


  def printer(self):
    return self.__heap[1:self.__size + 1]

  def heapsort(self):
    result = np.zeros(self.__size, dtype=int)
    original_size = self.__size
    for i in range(original_size):
        result[i] = self.deletion()
    return result



In [ ]:
arr = np.array([91, 52, 35, 6])
minheap = MinHeap(6)

for i in arr:
    minheap.insertion(i)

print("Heap elements:")
minheap.printer()  # Should print: 6 52 35 91

print("Extract Min:", minheap.extractMin())  # Should print: 6
minheap.insertion(70)

print("Heap after inserting 70:")
minheap.printer()  # Should print: 35 52 70 91

print("Extract Min:", minheap.extractMin())  # Should print: 35

print("Sorted output:")
sorted_arr = minheap.heapsort()
print(sorted_arr)  # Should print: [52 70 91]


Heap elements:
0 6 35 52 91 0 
Extract Min: 6
Heap after inserting 70:
0 6 35 52 91 70 
Extract Min: 6
Sorted output:
[ 6 35 52 70 91]


* TASK 02


In [ ]:
import numpy as np

class MaxHeap:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__heap = np.zeros(capacity+1, dtype=int)
        self.__size = 0

    def insertion(self, value):
        if self.__size == self.__capacity:
            return "Heap is full, Insertion is not possible."
        self.__size += 1
        self.__heap[self.__size] = value
        self.swim()

    def swim(self):
        child = self.__size
        parent = child // 2

        while self.__heap[parent] < self.__heap[child]:
            self.__heap[parent], self.__heap[child] = self.__heap[child], self.__heap[parent]
            child = parent
            parent = child // 2

    def deletion(self):
        if self.__size == 0:
            return "Heap is empty, Deletion is not possible"
        value = self.__heap[1]
        self.__heap[1], self.__heap[self.__size] = self.__heap[self.__size], self.__heap[1]
        self.__size -= 1
        self.sink()
        return value

    def sink(self):
        parent = 1
        while True:
            left = 2 * parent
            if left > self.__size:
                break
            right = left + 1

            max_child = left
            if right <= self.__size and self.__heap[right] > self.__heap[left]:
                max_child = right

            if self.__heap[parent] < self.__heap[max_child]:
                self.__heap[parent], self.__heap[max_child] = self.__heap[max_child], self.__heap[parent]
                parent = max_child
            else:
                break



    def printer(self):
        for i in self.__heap:
            print(i, end=" ")
        print()
    def extractMax(self):
        if self.__size == 0:
            return "Heap is empty"
        return self.__heap[1]

    def heapsort(self):
        result = np.zeros(self.__size, dtype=int)
        original_size = self.__size
        for i in range(original_size):
            result[i] = self.deletion()
        return result

In [ ]:
def distribute_tasks(tasks, m):
    # Step 1: Initialize a min-heap with m machines, all having initial load 0
    heap = MinHeap(m)
    for _ in range(m):
        heap.insertion(0)

    # Step 2: Assign each task to the machine with the smallest current load
    for task in tasks:
        # Extract the machine with the smallest load
        min_load = heap.deletion()
        # Add the task's processing time to this load
        updated_load = min_load + task
        # Reinsert the updated load back into the heap
        heap.insertion(updated_load)

    # Step 3: Return the final array representation of the heap
    return heap.printer()


# Example Usage
tasks = [2, 4, 7, 1, 6]
m = 4
result = distribute_tasks(tasks, m)
print(result)  # Output: [2, 4, 7, 7]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [ ]:
import numpy as np

class MinHeap:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__heap = np.zeros(capacity + 1, dtype=int)
        self.__size = 0

    def insertion(self, value):
        if self.__size == self.__capacity:
            return "Heap is full, Insertion is not possible."
        self.__size += 1
        self.__heap[self.__size] = value
        self.swim()

    def swim(self):
        child = self.__size
        parent = child // 2

        while parent >= 1 and self.__heap[parent] > self.__heap[child]:
            self.__heap[parent], self.__heap[child] = self.__heap[child], self.__heap[parent]
            child = parent
            parent = child // 2

    def deletion(self):
        if self.__size == 0:
            return "Heap is empty, Deletion is not possible"
        value = self.__heap[1]
        self.__heap[1], self.__heap[self.__size] = self.__heap[self.__size], self.__heap[1]
        self.__size -= 1
        self.sink()
        return value

    def sink(self):
        parent = 1
        while True:
            left = 2 * parent
            if left > self.__size:
                break
            right = left + 1

            min_child = left
            if right <= self.__size and self.__heap[right] < self.__heap[left]:
                min_child = right

            if self.__heap[parent] > self.__heap[min_child]:
                self.__heap[parent], self.__heap[min_child] = self.__heap[min_child], self.__heap[parent]
                parent = min_child
            else:
                break

    def extractMin(self):
        if self.__size == 0:
            return "Heap is empty"
        return self.__heap[1]

    def printer(self):
        return self.__heap[1:self.__size + 1]

    def heapsort(self):
        result = np.zeros(self.__size, dtype=int)
        original_size = self.__size
        for i in range(original_size):
            result[i] = self.deletion()
        return result



In [ ]:
arr = np.array([91, 52, 35, 6])
minheap = MinHeap(6)

for i in arr:
    minheap.insertion(i)

print("Heap elements:")
minheap.printer()

print("Extract Min:", minheap.extractMin())
minheap.insertion(70)

print("Heap after inserting 70:")
minheap.printer()

print("Extract Min:", minheap.extractMin())  #

print("Sorted output:")
sorted_arr = minheap.heapsort()
print(sorted_arr)


Heap elements:
Extract Min: 6
Heap after inserting 70:
Extract Min: 6
Sorted output:
[ 6 35 52 70 91]


In [ ]:
def distribute_tasks(tasks, m):
    heap = MinHeap(m)
    for _ in range(m):
        heap.insertion(0)

    for task in tasks:
        min_load = heap.deletion()
        updated_load = min_load + task
        heap.insertion(updated_load)

    return sorted(heap.printer())



tasks = [2, 4, 7, 1, 6]
m = 4
result = distribute_tasks(tasks, m)
print(result)

[np.int64(2), np.int64(4), np.int64(7), np.int64(7)]

In [ ]:
def find_top_k_largest(nums, k):
    # Step 1: Create a max-heap with the capacity equal to the size of nums
    n = len(nums)
    max_heap = MaxHeap(n)

    # Step 2: Insert all elements from nums into the max-heap
    for num in nums:
        max_heap.insertion(num)

    # Step 3: Extract the maximum k times and store the values in a result array
    result = np.zeros(k, dtype=int)
    for i in range(k):
        result[i] = max_heap.deletion()

    # Step 4: Return the result array
    return result


# Sample Input
nums = [4, 10, 2, 8, 6, 7]
k = 3

# Find the top k largest elements
output = find_top_k_largest(nums, k)
print(output)  # Output: [10, 8, 7]

[8 7 6]


In [ ]:

class MaxHeap:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__heap = np.zeros(capacity + 1, dtype=int)
        self.__size = 0

    def insertion(self, value):
        if self.__size == self.__capacity:
            return "Heap is full, Insertion is not possible."
        self.__size += 1
        self.__heap[self.__size] = value
        self.swim()

    def swim(self):
        child = self.__size
        parent = child // 2

        while parent > 0 and self.__heap[parent] < self.__heap[child]:
            self.__heap[parent], self.__heap[child] = self.__heap[child], self.__heap[parent]
            child = parent
            parent = child // 2

    def deletion(self):
        if self.__size == 0:
            return "Heap is empty, Deletion is not possible"
        value = self.__heap[1]
        self.__heap[1], self.__heap[self.__size] = self.__heap[self.__size], self.__heap[1]
        self.__size -= 1
        self.sink()
        return value

    def sink(self):
        parent = 1
        while True:
            left = 2 * parent
            if left > self.__size:
                break
            right = left + 1

            max_child = left
            if right <= self.__size and self.__heap[right] > self.__heap[left]:
                max_child = right

            if self.__heap[parent] < self.__heap[max_child]:
                self.__heap[parent], self.__heap[max_child] = self.__heap[max_child], self.__heap[parent]
                parent = max_child
            else:
                break

    def printer(self):
        for i in range(1, self.__size + 1):
            print(self.__heap[i], end=" ")
        print()


    def extractMax(self):
        if self.__size == 0:
            return "Heap is empty"
        return self.__heap[1]

    def heapsort(self):
        result = np.zeros(self.__size, dtype=int)
        original_size = self.__size
        for i in range(original_size):
            result[i] = self.deletion()
        return result




[10  8  7]


In [ ]:
def find_top_k_largest(nums, k):
    n = len(nums)
    max_heap = MaxHeap(n)

    for num in nums:
        max_heap.insertion(num)

    result = np.zeros(k, dtype=int)
    for i in range(k):
        result[i] = max_heap.deletion()

    return result



nums = [4, 10, 2, 8, 6, 7]
k = 3
output = find_top_k_largest(nums, k)
print(output)